### ISSUE TITLE
Azure Deployment of code after environment is already set up.

### ISSUE THREAD

**Issue by rroman81** [Sitecore/Sitecore.HabitatHome.Platform#134]
**Is your feature request related to a problem? Please describe.**
Currently, Azure scripts are geared towards installing initial environment with required modules, and habitat VS output as another module.  However, any subsequent changes to the code would require a modified version of automation to deliver changes only to modified roles.

**Describe the solution you'd like**
As part of DevOps culture, we want to build a multi-phase pipeline and have guidance around the effort.  Thus, the build cake tasks need to be evolved further to detect that infrastructure nested deployment may not need to run, and any web deploy packages that are needs to be re-deployed need to have their db operations removed.

**Describe alternatives you've considered**
I am working on augmenting the tasks for azure-upload.ps1 and azure-deploy.ps1 scripts to prepare not just the base web deploy packages but also the version that removes db operations and then run only "application" portion of the arm templates with updated wdps to faciliate the code deploy.

**Additional context**
This is a bit of a discussion on how the direction is invisioned by Sitecore team, and match the approach in this sample.

**Comment by jeanfrancoislarente** [comment]
Hey @rroman81 

I'm not opposed to including such functionality in this repo if you're proposing a contribution. 

Since this feature was put together mainly to support the deployment of Habitat Home (which as you know is a site pre-loaded with content) there was no immediate need to showcase the true blue/green deployments of code-only as most users of this repo would want to stand up Habitat Home as a sample and then tear it down.

Feel free to update / refactor as you see fit, as long as the original functionality remains similar / intact. Would be happy to have 1:1 discussions if you feel it's required, otherwise I understand where you're trying to go and I'm happy to review anything you propose!

Cheers!

**Comment by rroman81** [comment]
i think a good 1:1 converation would be in order. there are many ways to slice this.  I am working through the process on another solution and getting the samples to show further how to modify the arm templates from quickstarts to facilitate the code deploy portion only.

**Comment by jeanfrancoislarente** [comment]
DM me on Slack if you're there @jflsitecore - we can chat there.

**Comment by jeanfrancoislarente** [comment]
No longer relevant
