### ISSUE TITLE
Unicorn Sync Problem for 9.2

### ISSUE THREAD

**Issue by vtml** [Sitecore/Sitecore.HabitatHome.Platform#167]
I am getting the following error during the Unicorn sync task.

> TypeLoadException: Could not load type 'Sitecore.Data.Items.WebDAVSynchronizer' from assembly 'Sitecore.Kernel, Version=13.0.0.0, Culture=neutral, PublicKeyToken=null'.

I reflected the DLL of Sitecore.Kernel for 9.2 and Sitecore.Data.Items.WebDAVSynchronizer is no longer there. This is still present as of 9.1.1.

**Comment by viethoangpyco** [comment]
@jflheureux I suppose that Unicorn need to be upgraded to version 4.1.0 or later as well
![image](https://user-images.githubusercontent.com/6151021/65872038-e3a91d00-e3a9-11e9-9df8-623cf5cc04b0.png)

Otherwise, we will get the following issue:
![image](https://user-images.githubusercontent.com/6151021/65872076-fc193780-e3a9-11e9-9575-7d02ef155734.png)

**Comment by jflheureux** [comment]
I agree with you @viethoangpyco. It would be a good idea to upgrade Unicorn. This would be done in this upstream project: https://github.com/Sitecore/Sitecore.Demo.Shared/blob/master/src/Foundation/Serialization/code/Sitecore.Demo.Foundation.Serialization.csproj

However, I never experienced this Unicorn error using 9.2 and this demo.

**Comment by vtml** [comment]
I just installed Sitecore.HabitatHome.Corporate, which uses exactly the same Nuget packages generated from Sitecore.Demo.Shared. I can confirm Unicorn sync is working for 9.2. That means the problem is isolated to Sitecore.HabitatHome.Platform only.

However agree that it will be awesome to use the latest version of Unicorn.

**Comment by jeanfrancoislarente** [comment]
Fixed in master and release/9.2.0 branches
